# Generated by Django 6.0.2 on 2026-02-18 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_comment_alter_subject_options_remove_project_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.RemoveField(
            model_name='project',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='pupils',
            field=models.ManyToManyField(related_name='projects', to='projects.pupil', verbose_name='Авторы-ученики'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
