# Generated by Django 6.0.2 on 2026-02-24 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_students_remove_project_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='project',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_projects', to='projects.teacher', verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='project',
            name='moderation_comment',
            field=models.TextField(blank=True, help_text='Причина отклонения или замечания', verbose_name='Комментарий модератора'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонен'), ('revision', 'Требует доработки'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
